/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "rrnthnkajjbrfifkumbm"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJybnRobmthampicmZpZmt1bWJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjcwMjEzMzIsImV4cCI6MjA4MjU5NzMzMn0.rqZ-G9l9rdCuZd1aCU9fugALL6BObPy-wWtmCNPYLnE"